Esercizio3: Esercizio3.o random.o Esercizio3.hpp random.h
	g++ Esercizio3.o random.o -o Esercizio3
Esercizio3.o: Esercizio3.cpp random.cpp Esercizio3.hpp random.h
	g++ -c Esercizio3.cpp -o Esercizio3.o
	
random.o: random.cpp random.h
	g++ -c random.cpp -o random.o

clean:
	rm *.o

do:
	./Esercizio3


